plugins {
    kotlin("jvm")
}

/**
 * Delete the generated `Target` folder that is being generated by Rust Cargo
 */
val rustClean by tasks.register("rustClean") {
    group = "rust"
    delete(projectDir.resolve("target"))
}

tasks.matching {
    it.name == "clean"
}.all {
    dependsOn(rustClean)
}
